name: Verify links
on:
  pull_request:
    branches:
      - main

jobs:

  markdown-link-check:
    name: Verify links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1